### ISSUE TITLE
module could not be found: notifications_bindings.node

### ISSUE THREAD

**Issue by dulakm** [felixrieseberg/electron-windows-interactive-notifications#4]
Hello,

I have `electron-windows-interactive-notifications` as my dependency. When I use clean `npm install` and after that `electron-rebuild` I get:
```bash
App threw an error during load
Error: The specified module could not be found.
\\?\C:\Users\moro\projects\tw-en-ty\node_modules\electron-windows-interactive-notifications\build\Release\notifications_bindings.node
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at bindings (C:\Users\moro\projects\tw-en-ty\node_modules\bindings\bindings.js:76:44)
````

According to a [NodeJS issue](https://github.com/nodejs/node/issues/2964) it seems to be a native dependency problem. When I examine `notifications_bindings.node` by [dependencywalker](http://dependencywalker.com/) I see following missing direct DLLs (among many missing nested):

![image](http://i.imgur.com/P2hl7VBl.png)

Please, is it a problem with `electron-windows-interactive-notifications` or something else?

Also I found myself very confused resolving `electron-windows-interactive-notifications` issues as it is crossover of native and JS technologies which highly depends on the way an environment was set. Is there any OOTB-working sample for `electron-windows-interactive-notifications` that I could use as a reference?

Thank you!

**Comment by lissy93** [comment]
Can you confirm that this is not just a Windows permissions issue?

**Comment by dulakm** [comment]
@Lissy93 thanks for the response! I'm running everything as admin.

I tried finding missing dependencies on my file system and found them on following places:
- node.dll - `node_modules\electron\dist\`
- interactivenotifications.dll - `node_modules\electron-windows-interactive-notifications\Rele‌​ase\`
- api-...-.dll - `c:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64\api-ms-win-crt-runtime-l1-1-0.d‌​ll`

I'm thinking whether they shouldn't be relatively/absolutely referenced the same way `kernel32.dll`, `ole32.dll` or `vcruntime140.dll` are. What do you think? 

By the way, can you help me get into the technologies? What is responsible for correct DLL linkings? Is it [library itself](https://github.com/felixrieseberg/electron-windows-interactive-notifications), [NodeRT](https://github.com/NodeRT/NodeRT) or [node-gyp](https://github.com/nodejs/node-gyp)?

**Comment by DesselBane** [comment]
Are there any news ? Having the same problem and still looking for a fix

**Comment by DesselBane** [comment]
Tried to simply copy the missing dependencies into the /node_modules/electron-windows-interactive-notifications/build/Release folder but ended up getting a new error


![image](https://user-images.githubusercontent.com/12199480/39052643-0077223a-44ad-11e8-9513-dbe5537fde41.png)

**Comment by jlsilva1994** [comment]
Hello, i have the same problem here,  @felixrieseberg  can you give some feedback? This kind of notifications are important, and your module seems to be the only who addresses this subject

**Comment by wiinf** [comment]
Hello at all,

After 6 hours playing around this issue, i found a solution.  

The real problem is a missing InteractiveNotifications.dll which sould be copied by postinstall.js. postinstall.js is located in "electron-windows-interactive-notifications\scripts". 

After study this file, i recognized that there are a x86 and x64 Bit version of the missing dll. 

On x86 installations, copy 
`node_modules\electron-windows-interactive-notifications\Release\InteractiveNotifications.dll` 
 to 
` electron-windows-interactive-notifications\build\Release`

On x64 installations, copy 
`node_modules\electron-windows-interactive-notifications\x64\Release\InteractiveNotifications.dll` 
 to
`  electron-windows-interactive-notifications\build\Release`

@DesselBane , i had the same error with the x86 dll use 64bit one and it will work.

Sry for my english!

Greetings
