### ISSUE TITLE
npm install failing on Windows 10

### ISSUE THREAD

**Issue by kanishk98** [felixrieseberg/electron-windows-interactive-notifications#8]
Hi, 

I'm just getting started with this module, but I can't get it to install on my system. I've made sure that I'm running the VS Code Developer Command Prompt as admin, that my system can recognize the `msbuild` command, and other `npm install`(s) work fine. 

Here's my error log: 

```
1022 verbose stack Error: electron-windows-interactive-notifications@0.7.7 preinstall: `node ./scripts/preinstall.js && npm run build`
1022 verbose stack Exit status 1
1022 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
1022 verbose stack     at emitTwo (events.js:126:13)
1022 verbose stack     at EventEmitter.emit (events.js:214:7)
1022 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
1022 verbose stack     at emitTwo (events.js:126:13)
1022 verbose stack     at ChildProcess.emit (events.js:214:7)
1022 verbose stack     at maybeClose (internal/child_process.js:925:16)
1022 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
1023 verbose pkgid electron-windows-interactive-notifications@0.7.7
1024 verbose cwd <myDirectory>
1025 verbose Windows_NT 10.0.14393
1026 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "electron-windows-interactive-notifications"
1027 verbose node v8.11.3
1028 verbose npm  v5.6.0
1029 error code ELIFECYCLE
1030 error errno 1
1031 error electron-windows-interactive-notifications@0.7.7 preinstall: `node ./scripts/preinstall.js && npm run build`
1031 error Exit status 1
1032 error Failed at the electron-windows-interactive-notifications@0.7.7 preinstall script.
1032 error This is probably not a problem with npm. There is likely additional logging output above.
1033 verbose exit [ 1, true ]
```

**Comment by abduljanjua** [comment]
Did you find any solution for this?

**Comment by kanishk98** [comment]
@abduljanjua I wasn't able to, sorry. Moved on from this feature in my project after a couple of days of not getting it to work.

**Comment by DesselBane** [comment]
Just a wild guess: You use the Visual Studio 2017 dev tools ? I think I remember that it was written using VS2015 and would't compile with the 2017 dev tools on my system (it compiles the module when you install it). Maybe wanna try it using the VS2015 dev tools

**Comment by kanishk98** [comment]
@DesselBane that's probably it, thanks! I'll try compiling again using the 2015 tools. Will post back here if something breaks again.
